package main

import (
	// Default Flogo activities
	_ "github.com/TIBCOSoftware/flogo-contrib/action/flow"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/actreply"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/actreturn"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/aggregate"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/app"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/awsiot"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/awssns"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/coap"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/couchbase"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/counter"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/error"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/gpio"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/kafkapub"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/lambda"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/log"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/mapper"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/reply"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/rest"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/subflow"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/twilio"
	_ "github.com/TIBCOSoftware/flogo-contrib/activity/wsmessage"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/cli"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/coap"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/kafkasub"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/lambda"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/mqtt"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/rest"
	_ "github.com/TIBCOSoftware/flogo-contrib/trigger/timer"
	// Activities from retgits/flogo-components
	_ "github.com/retgits/flogo-components/activity/addtodate"
	_ "github.com/retgits/flogo-components/activity/amazons3"
	_ "github.com/retgits/flogo-components/activity/amazonsqssend"
	_ "github.com/retgits/flogo-components/activity/amazonssm"
	_ "github.com/retgits/flogo-components/activity/dynamodbinsert"
	_ "github.com/retgits/flogo-components/activity/dynamodbquery"
	_ "github.com/retgits/flogo-components/activity/githubissues"
	_ "github.com/retgits/flogo-components/activity/gzip"
	_ "github.com/retgits/flogo-components/activity/randomnumber"
	_ "github.com/retgits/flogo-components/activity/randomstring"
	_ "github.com/retgits/flogo-components/activity/trellocard"
)
